export const cafeMenu = [
    {
        category: 'Pizza',
        items: [
            {
                name: 'Veg Pizza Mini',
                description: 'Bite-sized pizza crust topped with veggies, tangy tomato sauce, melted cheese, and Italian herbs for a savory treat.',
                price: 69,
                imageurl: './menu/Pizza/Veg Pizza Mini.png',
                category: 'Pizza',
                type: 'veg',
            },
            {
                name: 'Chicken Pizza Mini',
                description: 'Mini pizza with crispy crust, chicken chunks, rich tomato sauce, and melted mozzarella cheese.',
                price: 99,
                imageurl: './menu/Pizza/Chicken Pizza Mini.png',
                category: 'Pizza',
                type: 'non-veg',
            },
            {
                name: 'Chicken Momo Pizza',
                description: 'A fusion delight combining chicken momos with pizza crust, topped with tangy sauce, cheese, and spices.',
                price: 109,
                imageurl: './menu/menuitems/momopizza.jpg',
                category: 'Pizza',
                type: 'non-veg',
            },
        ],
    },
    {
        category: 'Litti',
        items: [
            {
                name: 'Litti Chokha',
                description: 'Traditional dish served with two pieces of litti, paired with begun bhartha, aloo bhartha, and green chutney.',
                price: 99,
                imageurl: '/menu/menuitems/litthi.jpg',
                category: 'Litti',
                type: 'veg',
            },
        ],
    },
    {
        category: 'Fuchka',
        items: [
            {
                name: 'Fuchka',
                description: 'Crispy puris served with imli pani, pudina pani, misti pani, and a flavorful aloo bhartha filling.',
                price: 59,
                imageurl: '/menu/menuitems/fuchka.jpg',
                category: 'Fuchka',
                type: 'veg',
            },
            {
                name: 'Doi Fuchka',
                description: 'Fuchka filled with sweet curd and tangy tamarind chutney, topped with spices.',
                price: 79,
                imageurl: '/menu/menuitems/DoiFhucka.jpg',
                category: 'Fuchka',
                type: 'veg',
            },
            {
                name: 'Papdi Chaat',
                description: 'A mix of crispy papdi, curd, tangy chutneys, and spices for a perfect snack.',
                price: 79,
                imageurl: '/menu/menuitems/papdi.jpg',
                category: 'Fuchka',
                type: 'veg',
            },
        ],
    },
    {
        category: 'French Fries',
        items: [
            {
                name: 'French Fries (Regular)',
                description: 'Crispy golden fries seasoned with salt.',
                price: 69,
                imageurl: './menu/menuitems/ff.jpg',
                category: 'French Fries',
                type: 'veg',
            },
            {
                name: 'French Fries (Medium)',
                description: 'Medium portion of crispy fries, perfect for sharing.',
                price: 89,
                imageurl: './menu/menuitems/ff.jpg',
                category: 'French Fries',
                type: 'veg',
            },
            {
                name: 'French Fries (Large)',
                description: 'Generous portion of crispy fries, ideal for a group.',
                price: 109,
                imageurl: './menu/menuitems/ff.jpg',
                category: 'French Fries',
                type: 'veg',
            },
        ],
    },
    {
        category: 'Momo',
        items: [
            {
                name: 'Veg Momo',
                description: 'Steamed dumplings stuffed with finely chopped vegetables and spices.',
                price: 69,
                imageurl: './menu/menuitems/momo.jpg',
                category: 'Momo',
                type: 'veg',
            },
            {
                name: 'Veg Cheese Momo',
                description: 'Vegetable-filled momos with a creamy cheese center.',
                price: 79,
                imageurl: './menu/menuitems/vegcheese.jpg',
                category: 'Momo',
                type: 'veg',
            },
            {
                name: 'Corn Momo',
                description: 'Delicious momos filled with spiced corn stuffing.',
                price: 69,
                imageurl: './menu/menuitems/cm.jpg',
                category: 'Momo',
                type: 'veg',
            },
            {
                name: 'Corn Cheese Momo',
                description: 'Corn-filled momos with a cheesy twist.',
                price: 79,
                imageurl: './menu/menuitems/corncm.jpg',
                category: 'Momo',
                type: 'veg',
            },
            {
                name: 'Chicken Momo',
                description: 'Steamed dumplings stuffed with seasoned chicken.',
                price: 89,
                imageurl: './menu/menuitems/chm.jpg',
                category: 'Momo',
                type: 'non-veg',
            },
            {
                name: 'Chicken Cheese Momo',
                description: 'Juicy chicken momos with melted cheese filling.',
                price: 109,
                imageurl: './menu/menuitems/ccm.jpg',
                category: 'Momo',
                type: 'non-veg',
            },
        ],
    },
    {
        category: 'Burger',
        items: [
            {
                name: 'Veg Mini Burger',
                description: 'Mini burger with a crispy veggie patty, lettuce, and tangy mayo.',
                price: 99,
                imageurl: './menu/menuitems/vb.jpg',
                category: 'Burger',
                type: 'veg',
            },
            {
                name: 'Chicken Momo Burger',
                description: 'Unique burger with chicken momos, lettuce, and spicy mayo.',
                price: 119,
                imageurl: './menu/menuitems/mb.jpg',
                category: 'Burger',
                type: 'non-veg',
            },
            {
                name: 'Chicken Burger',
                description: 'Classic chicken burger with a juicy chicken patty and fresh toppings.',
                price: 119,
                imageurl: './menu/menuitems/vb2.jpg',
                category: 'Burger',
                type: 'non-veg',
            },
            {
                name: 'Peri Peri Chicken Burger',
                description: 'Burger with a zesty peri peri chicken patty and creamy sauce.',
                price: 139,
                imageurl: './menu/menuitems/vb3.jpg',
                category: 'Burger',
                type: 'non-veg',
            },
        ],
    },
    {
        category: 'Sandwich',
        items: [
            {
                name: 'Veg Sandwich',
                description: 'Simple and fresh sandwich with vegetables and chutney.',
                price: 59,
                imageurl: './menu/menuitems/sandw.jpg',
                category: 'Sandwich',
                type: 'veg',
            },
            {
                name: 'Veg Coleslaw Sandwich',
                description: 'Creamy coleslaw filling in soft bread slices.',
                price: 69,
                imageurl: './menu/menuitems/sandw.jpg',
                category: 'Sandwich',
                type: 'veg',
            },
            {
                name: 'Chicken Sandwich',
                description: 'Juicy chicken filling in a sandwich, served with spices.',
                price: 79,
                imageurl: './menu/menuitems/sandw.jpg',
                category: 'Sandwich',
                type: 'non-veg',
            },
        ],
    },
    {
        category: 'Beverages',
        items: [
            {
                name: 'Tea',
                description: 'Hot, refreshing tea with a blend of spices and sugar.',
                price: 20,
                imageurl: './menu/menuitems/tea.jpg',
                category: 'Beverages',
                type: 'veg',
            },
            {
                name: 'Coffee',
                description: 'Freshly brewed coffee with a rich aroma.',
                price: 30,
                imageurl: './menu/menuitems/coffee.jpg',
                category: 'Beverages',
                type: 'veg',
            },
            {
                name: 'Mocktails',
                description: 'Refreshing non-alcoholic drinks with fruity flavors.',
                price: 50,
                imageurl: './menu/menuitems/mock.jpg',
                category: 'Beverages',
                type: 'veg',
            },
        ],
    },
];


export const cafeCategories = [
    { category: 'Pizza', priority: 1 },
    { category: 'Litti', priority: 2 },
    { category: 'Fuchka', priority: 3 },
    { category: 'French Fries', priority: 4 },
    { category: 'Momo', priority: 5 },
    { category: 'Burger', priority: 6 },
    { category: 'Sandwich', priority: 7 },
    { category: 'Combo Meals', priority: 8 },
    { category: 'Beverages', priority: 9 },
];